server:
  port: 10018

spring:
  profiles:
    active: dev
  application:
    name: nacos-mcp-server
  ai:
    mcp:
      server:
        name: nacos-mcp-server
        version: 1.0.0
        type: async
        instructions: "计算器"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        nacos:
          server-addr: 127.0.0.1:8848
          namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
          register:
            enabled: true
            service-group: mcp-server
            service-name: webflux-mcp-server


