spring:
  ai:
    dashscope:
      api-key: ${AI_DASH_SCOPE_API_KEY}
#      embedding:
#        options:
#          model: text-embedding-v4
#          dimensions: 1024
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
    # 使用自定义增强的 mcp server config 替换
    # mcp:
    #   client:
    #     stdio:
    #       servers-configuration: classpath:/mcp-servers-config.json
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        table-name: vector_store
        initialize-schema: true

    mcp:
      client:
        toolcallback:
          enabled: true

    alibaba:
     playground:

       # IQS 数据搜索服务配置
       iqs:
         search:
           api-key: ${IQS_SEARCH_API_KEY}

       # 百炼知识库
       bailian:
         enable: true
         index-name: spring-ai-learn

    # 注意：观测数据可能存在敏感信息！
    chat:
      client:
        observations:
          # 记录调用输入
          include-input: true
      observations:
        # 记录 LLMs 输出
        include-completion: true
        # 记录 prompt
        include-prompt: true
        include-error-logging: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/playground
    username: pgsql
    password: 123456

  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.PostgreSQLLegacyDialect

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.application: debug

# 部署时不配置，使用默认配置
management:
  endpoints:
    web:
      exposure:
        # 开放所有外部端点
        include: "*"
  endpoint:
    health:
      # 应用健康状态检查，携带详细新学年
      show-details: always
  tracing:
    sampling:
      # trace 采样信息，记录每个请求
      probability: 1.0


app:
  # 需要配置相关 tools 的信息
  tool-calling:
    baidu:
      translate:
        ak: ${BAIDU_TRANSLATE_APP_ID:input-your-baidu-app-id}
        sk: ${BAIDU_TRANSLATE_SECRET_KEY:input-your-baidu-app-key}
      map:
        ak: ${BAIDU_MAP_API_KEY:input-your-baidu-map-key}